src/main/java/com/imooc/sell/dto/OrderDTO.java

/**
 * Project Name:sell.<br/> 
 * File Name:OrderDTO.java.<br/> 
 * Package Name:com.imooc.sell.dto.<br/> 
 * Date:2017年12月11日下午5:03:28.<br/> 
 * Copyright (c) 2017, 版权所有 (C) 2016-2036  土豆互联科技(深圳)有限公司 www.potato369.com All Rights Reserved.<br/> 
 */ 
    
package com.imooc.sell.dto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import javax.persistence.Id;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.imooc.sell.dataobject.OrderDetail;
import com.imooc.sell.enums.OrderStatusEnum;
import com.imooc.sell.enums.PayStatusEnum;
import com.imooc.sell.utils.EnumUtil;
import com.imooc.sell.utils.serializer.Date2LongSerializer;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * <pre>
 * @ClassName:OrderDTO
 * @Function:
 * @Reason:
 * @Date: 2017年12月11日 下午5:03:28
 * @Desc:
 * @author 王艳军
 * @version
 * @since JDK 1.6
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
//@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
//@JsonInclude(JsonInclude.Include.NON_NULL)
public class OrderDTO {

  /**
   * orderId：订单编号
   */
  @Id
  private String orderId;
  
  /**
   * buyerName：买家名字
   */
  private String buyerName;
  
  /**
   * buyerPhone：买家电话
   */
  private String buyerPhone;
  
  /**
   * buyerAddress：买家地址
   */
  private String buyerAddress;
  
  /**
   * buyerOpenid：买家微信openid
   */
  private String buyerOpenid;
  
  /**
   * orderAmount：订单总金额
   */
  private BigDecimal orderAmount;
  
  /**
   * orderStatus：订单状态，默认是新下单
   */
  private Integer orderStatus;
  
  /**
   * payStatus：支付状态，默认0为未支付
   */
  private Integer payStatus;
  
  /**
   * createTime：创建时间
   */
  @JsonSerialize(using = Date2LongSerializer.class)
  private Date createTime;
  
  /**
   * updateTime：更新时间
   */
  @JsonSerialize(using = Date2LongSerializer.class)
  private Date updateTime;
  
  @Transient
  private List<OrderDetail> orderDetailList;

  @JsonIgnore
  public OrderStatusEnum getOrderStatusEnum(){
    return EnumUtil.getByCode(orderStatus, OrderStatusEnum.class);
  }

  @JsonIgnore
  public PayStatusEnum getPayStatusEnum(){
    return EnumUtil.getByCode(payStatus, PayStatusEnum.class);
  }

  /**
   * cip：买家微信客户端ip
   */
  private String cip;

  /**
   * fingerPrint：浏览器指纹
   */
  private String fingerPrint;

  /**
   * jsonSceneInfo：json格式场景信息字符串
   */
  private String jsonSceneInfo;
}

src/main/java/com/imooc/sell/form/OrderForm.java

/**
 * <pre>
 * Project Name:sell
 * File Name:OrderForm.java
 * Package Name:com.imooc.sell.form
 * Date:2017年12月12日下午4:32:46
 * Copyright (c) 2017, 版权所有 (C) 2016-2036  土豆互联科技(深圳)有限公司 www.potato369.com All Rights Reserved
 * </pre>
 */

package com.imooc.sell.form;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.validator.constraints.NotEmpty;

/**
 * <pre>
 * ClassName:OrderForm
 * Function:
 * Reason:
 * Date: 2017年12月12日 下午4:32:46
 * Desc:
 * @author 王艳军
 * @version
 * @since JDK 1.6
 * </pre>
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class OrderForm {

  /**
   * <pre>
   *  name：买家姓名
   * </pre>
   */
  @NotEmpty(message = "姓名必填")
  private String name;

  /**
   * <pre>
   *  phone：买家手机号
   * </pre>
   */
  @NotEmpty(message = "手机号必填")
  private String phone;

  /**
   * <pre>
   *  address：买家收获地址
   * </pre>
   */
  @NotEmpty(message = "地址必填")
  private String address;

  /**
   * <pre>
   *  openid：买家微信openid
   * </pre>
   */
  @NotEmpty(message = "微信openid必填")
  private String openid;

  /**
   * <pre>
   * items：买家购物车
   * </pre>
   */
  @NotEmpty(message = "购物车不能为空")
  private String items;
}

src/main/resources/templates/order/detail.ftl
<html>
    <#include "../common/header.ftl">
<body>
    <div id="wrapper" class="toggled">
        <#--边栏 sidebar-->
        <#include "../common/nav.ftl">
        <#--主体内容区域 content-->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row clearfix">
                <#--订单数据-->
                    <div class="col-md-8 column">
                        <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th style="text-align: center">
                                    订单id
                                </th>
                                <th style="text-align: center">
                                    订单总金额
                                </th>
                                <th style="text-align: center">
                                    订单状态
                                </th>
                                <th style="text-align: center">
                                    支付状态
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr class="success" style="text-align: center">
                                <td>
                                ${orderDTO.orderId}
                                </td>
                                <td>
                                ${orderDTO.orderAmount}
                                </td>
                                <td>
                                ${orderDTO.orderStatusEnum.message}
                                </td>
                                <td>
                                ${orderDTO.payStatusEnum.getMessage()}
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                <#--订单详情表数据-->
                    <div class="col-md-12 column">
                        <table class="table table-hover table-bordered">
                            <thead>
                            <tr>
                                <th style="text-align: center">商品id</th>
                                <th style="text-align: center">商品名称</th>
                                <th style="text-align: center">价格</th>
                                <th style="text-align: center">数量</th>
                                <th style="text-align: center">总额</th>
                            </tr>
                            </thead>
                            <tbody>
                            <#list orderDTO.orderDetailList as orderDetail>
                                <tr class="warning" style="text-align: center">
                                    <td>
                                        ${orderDetail.productId}
                                    </td>
                                    <td>
                                        ${orderDetail.productName}
                                    </td>
                                    <td>
                                        ${orderDetail.productPrice}
                                    </td>
                                    <td>
                                        ${orderDetail.productQuantity}
                                    </td>
                                    <td>
                                        ${orderDetail.productPrice * orderDetail.productQuantity}
                                    </td>
                                </tr>
                            </#list>
                            </tbody>
                        </table>
                    </div>
                <#--按钮操作-->
                    <div class="col-md-12 column">
                        <#if orderDTO.getOrderStatusEnum().code == 0>
                            <a type="button" class="btn btn-primary btn-default active" href="/sell/seller/order/finish?orderId=${orderDTO.orderId}">完结订单</a>
                            <a type="button" class="btn btn-default active btn-danger" href="/sell/seller/order/cancel?orderId=${orderDTO.orderId}">取消订单</a>
                        </#if>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

src/main/resources/templates/order/list.ftl
<html>
    <#include "../common/header.ftl">
    <body>
        <div id="wrapper" class="toggled">
            <#--边栏 sidebar-->
            <#include "../common/nav.ftl">
            <#--主体内容区域 content-->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row clearfix">
                        <!--表格数据-->
                        <div class="col-md-12 column">
                            <table class="table table-bordered table-hover table-condensed">
                                <thead>
                                <tr>
                                    <th>订单id</th>
                                    <th>姓名</th>
                                    <th>手机号</th>
                                    <th>地址</th>
                                    <th>金额</th>
                                    <th>订单状态</th>
                                    <th>支付状态</th>
                                    <th>创建时间</th>
                                    <th>修改时间</th>
                                    <th colspan="2">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <#list orderDTOPage.content as orderDTO>
                                        <tr class="success">
                                            <td>${orderDTO.orderId}</td>
                                            <td>${orderDTO.buyerName}</td>
                                            <td>${orderDTO.buyerPhone}</td>
                                            <td>${orderDTO.buyerAddress}</td>
                                            <td>${orderDTO.orderAmount}</td>
                                            <td>${orderDTO.getOrderStatusEnum().message}</td>
                                            <td>${orderDTO.getPayStatusEnum().message}</td>
                                            <td>${orderDTO.createTime}</td>
                                            <td>${orderDTO.updateTime}</td>
                                            <td><a href="/sell/seller/order/detail?orderId=${orderDTO.orderId}">详情</a></td>
                                            <td>
                                                <#if orderDTO.getOrderStatusEnum().code == 0>
                                                    <a href="/sell/seller/order/cancel?orderId=${orderDTO.orderId}">取消</a>
                                                </#if>
                                            </td>
                                        </tr>
                                    </#list>
                                </tbody>
                            </table>
                        </div>
                        <!--分页-->
                        <div class="col-md-12 column">
                            <ul class="pagination pull-right">
		                        <#if currentPage lte 1>
		                            <li class="disabled"><a href="#">上一页</a></li>
		                        <#else>
		                            <li><a href="/sell/seller/order/list?page=${currentPage - 1}&size=${size}">上一页</a></li>
		                        </#if>
			                    <#if orderDTOPage.totalPages gt 0>
                                    <#list 1..orderDTOPage.totalPages as index>
                                        <#if currentPage == index>
			                            <li class="disabled"><a href="#">${index}</a></li>
                                        <#else>
			                            <li><a href="/sell/seller/order/list?page=${index}&size=${size}">${index}</a></li>
                                        </#if>
                                    </#list>
                                <#else>
                                    <li class="disabled"><a href="#">${currentPage}</a></li>
			                    </#if>
		                        <#if currentPage gte orderDTOPage.totalPages>
		                            <li class="disabled"><a href="#">下一页</a></li>
		                        <#else>
		                            <li><a href="/sell/seller/order/list?page=${currentPage + 1}&size=${size}">下一页</a></li>
		                        </#if>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <#--弹窗-->
        <div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title" id="myModalLabel">【温馨提醒】</h4>
                    </div>
                    <div class="modal-body">你有新的订单</div>
                    <div class="modal-footer">
                        <button onclick="javascript:document.getElementById('notice').pause()" type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                        <button onclick="location.reload()" type="button" class="btn btn-primary">查看新的订单</button>
                    </div>
                </div>
            </div>
        </div>

        <#--播放音乐-->
        <audio id="notice" loop="loop"><source src="/sell/mp3/song.mp3" type="audio/mpeg" /></audio>

        <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

        <script src="https://cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <script type="application/javascript">
            var websocket = null;
            if ("websocket" in window){
                   //开发环境（dev）：
                    websocket = new WebSocket("wss://potato369.mynatapp.cc/sell/websocket");
                   //测试环境（test）： websocket = new WebSocket("wss://potato369.mynatapp.cc/sell/websocket");
                   //生产环境（prod）：websocket = new WebSocket("wss://www.potato369.com/sell/websocket");
            } else {
                alert("浏览器不支持WebSocket！！！");
            }
            websocket.onopen = function (ev) {
                console.log("建立连接！！！");
            }
            websocket.onclose = function (ev) {
                console.log("关闭连接！！！");
            }
            websocket.onmessage = function (ev) {
                console.log("收到消息：",ev.data);
                // 弹窗提醒，同时播放音乐
                $('#myModal').modal('show');
                document.getElementById("notice").play();
            }
            websocket.onerror = function (ev) {
                alert("WebSocket通讯发生错误！！！");
            }
            window.onbeforeunload = function (ev) {
                websocket.close();
            }
        </script>
    </body>
</html>

src/main/resources/templates/order/malist.ftl
<html>
    <#include "../common/header.ftl">
    <body>
        <div id="wrapper" class="toggled">
            <#--边栏 sidebar-->
            <#include "../common/nav.ftl">
            <#--主体内容区域 content-->
            <div id="page-content-wrapper">
                <div class="container-fluid">
                    <div class="row clearfix">
                        <!--表格数据-->
                        <div class="col-md-12 column">
                            <table class="table table-bordered table-hover table-condensed">
                                <thead>
                                <tr>
                                    <th>订单id</th>
                                    <th>姓名</th>
                                    <th>手机号</th>
                                    <th>地址</th>
                                    <th>金额</th>
                                    <th>订单状态</th>
                                    <th>支付状态</th>
                                    <th>创建时间</th>
                                    <th colspan="3">操作</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <#list orderDTOPage.content as orderDTO>
                                        <tr class="success">
                                            <td>${orderDTO.orderId}</td>
                                            <td>${orderDTO.buyerName}</td>
                                            <td>${orderDTO.buyerPhone}</td>
                                            <td>${orderDTO.buyerAddress}</td>
                                            <td>${orderDTO.orderAmount}</td>
                                            <td>${orderDTO.getOrderStatusEnum().getMessage()}</td>
                                            <td>${orderDTO.getPayStatusEnum().getMessage()}</td>
                                            <td>${orderDTO.createTime}</td>
                                            <td><a href="/sell/seller/order/detail?orderId=${orderDTO.orderId}">详情</a></td>
                                            <td>
                                                <#if orderDTO.getOrderStatusEnum().getMessage() =="新下单">
                                                    <a href="/sell/seller/order/cancel?orderId=${orderDTO.orderId}">取消</a>
                                                </#if>
                                            </td>
                                            <td><a href="/sell/seller/order/detail?orderId=${orderDTO.orderId}">去支付</a></td>
                                        </tr>
                                    </#list>
                                </tbody>
                            </table>
                        </div>
                        <!--分页-->
                        <div class="col-md-12 column">
                            <ul class="pagination pull-right">
		                        <#if currentPage lte 1>
		                            <li class="disabled"><a href="#">上一页</a></li>
		                        <#else>
		                            <li><a href="/sell/seller/order/list?page=${currentPage - 1}&size=${size}">上一页</a></li>
		                        </#if>
			                    <#list 1..orderDTOPage.totalPages as index>
			                        <#if currentPage == index>
			                            <li class="disabled"><a href="#">${index}</a></li>
			                        <#else>
			                            <li><a href="/sell/seller/order/list?page=${index}&size=${size}">${index}</a></li>
			                        </#if>
			                    </#list>
		                        <#if currentPage gte orderDTOPage.totalPages>
		                            <li class="disabled"><a href="#">下一页</a></li>
		                        <#else>
		                            <li><a href="/sell/seller/order/list?page=${currentPage + 1}&size=${size}">下一页</a></li>
		                        </#if>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>